name: Lint Code Base

permissions: read-all

on:
  pull_request:

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Lint Code Base
        uses: super-linter/super-linter@ffde3b2b33b745cb612d787f669ef9442b1339a6
        env:
          VALIDATE_CPP: false
          VALIDATE_ALL_CODE_BASE: false
          LOG_LEVEL: NOTICE
